<?php

namespace Simon\PediBundle\Repository;

/**
 * GeometryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeometryRepository extends \Doctrine\ORM\EntityRepository
{
}
